#! /usr/bin/python
# -*- coding: utf-8 -*-

costs = {'Bas':2,
         'Skol':2,
         'Yrke':2,
         'Special_skol':1,
         'Special_yrke':1,
         'Special_hobb':1,
         'konst_rörl':6,
         'snabb_uth':6,
         'finm_grovm':6,
         'perc_konc':6,
         'prak_teor':6,
         'log_emo':6,
         'Syn':3,
         'Hörsel':3,
         'Lukt':3,
         'Känsel':3,
         'Smak':3,
         'Utseende':3}

start_traits = {'Bas':0,
                'Skol':0,
                'Yrke':0,
                'Special_skol':0,
                'Special_yrke':0,
                'Special_hobb':0,
                'Fysisk':12,
                'Mental':12,
                'Konstitution':4,
                'Rörlighet':4,
                'Snabbhet':4,
                'Uthållighet':4,
                'Finmotorik':4,
                'Grovmotorik':4,
                'Perception':4,
                'Koncentration':4,
                'Praktisk':4,
                'Teoretisk':4,
                'Logisk':4,
                'Emotionell':4,
                'Syn':4,
                'Hörsel':4,
                'Lukt':4,
                'Känsel':4,
                'Smak':4,
                'Utseende':4}

doubles = {'fys_ment':['Fysisk', 'Mental'],
           'konst_rörl':['Konstitution', 'Rörlighet'],
           'snabb_uth':['Snabbhet', 'Uthållighet'],
           'finm_grovm':['Finmotorik', 'Grovmotorik'],
           'perc_konc':['Perception', 'Koncentration'],
           'prak_teor':['Praktisk', 'Teoretisk'],
           'log_emo':['Logisk', 'Emotionell']
           }

sliders = {'fys_ment': ['Fysisk', 'Mental'],
           'konst_rörl': ['Konstitution', 'Rörlighet'],
           'snabb_uth': ['Snabbhet', 'Uthållighet'],
           'finm_grovm': ['Finmotorik', 'Grovmotorik'],
           'perc_konc': ['Perception', 'Koncentration'],
           'prak_teor': ['Praktisk', 'Teoretisk'],
           'log_emo' : ['Logisk', 'Emotionell']
           }


senses = ['Syn', 'Hörsel', 'Lukt', 'Känsel', 'Smak', 'Utseende']

skills_bases = {'Avståndsvapen':['Finmotorik', 'Koncentration'],
                'Avväpna':['Snabbhet', 'Praktisk'],
                'Bärsärkargång':['Emotionell', 'Koncentration'],
                'Dra vapen':['Rörlighet', 'Praktisk'],
                'Finta':['Rörlighet', 'Perception'],
                'Handgemäng':['Rörlighet', 'Praktisk'],
                'Huggvapen':['Grovmotorik', 'Praktisk'],
                'Krossvapen':['Grovmotorik', 'Praktisk'],
                'Stångvapen':['Grovmotorik', 'Praktisk'],
                'Kastvapen':['Finmotorik', 'Praktisk'],
                'Knocka':['Finmotorik', 'Praktisk'],
                'Sköldar':['Grovmotorik', 'Praktisk'],
                'Stickvapen':['Finmotorik', 'Praktisk'],
                'Två vapen':['Koncentration', 'Praktisk'],
                'Akademiska minnesfärdigheter':['Koncentration', 'Logisk'],
                'Akademiskt Teoretiska färdigheter':['Teoretisk', 'Logisk'],
                'Dansa':['Rörlighet', 'Koncentration'],
                'Fingerfärdighet':['Finmotorik', 'Praktisk'],
                'Finna dolt':['Perception', 'Perception'],
                'Förfalskning':['Finmotorik', 'Koncentration'],
                'Gömma sig':['Rörlighet', 'Emotionell'],
                'Hantera fällor':['Finmotorik', 'Logisk'],
                'Kasta':['Rörlighet', 'Praktisk'],
                'Knopar':['Finmotorik', 'Teoretisk'],
                'Kroppskontroll':['Rörlighet', 'Praktisk'],
                'Kulturkännedom':['Teoretisk', 'Emotionell'],
                'Läkekonst':['Finmotorik', 'Logisk'],
                'Marschera':['Uthållighet', 'Koncentration'],
                'Matlagning':['Smak', 'Logisk'],
                'Modersmål':['Koncentration', 'Logisk'],
                'Orientering':['Perception', 'Teoretisk'],
                'Spåra':['Perception', 'Syn'],
                'Underhålla':['Koncentration', 'Emotionell'],
                'Undre världen':['Koncentration', 'Logisk'],
                'Uppmärksamhet mot andra':['Perception', 'Emotionell'],
                'Övertala':['Emotionell', 'Emotionell']
                }

hitpoints = {'Huvud':0,
             'Hals':0,
             'Vänster axel':0,
             'Höger axel':0,
             'Bröstkorg':0,
             'Vänster överarm':0,
             'Höger överarm':0,
             'Mage':0,
             'Vänster underarm':0,
             'Höger underarm':0,
             'Vänster hand':0,
             'Höger hand':0,
             'Höft':0,
             'Vänster lår':0,
             'Höger lår':0,
             'Vänster smalben':0,
             'Höger smalben':0,
             'Vänster fot':0,
             'Höger fot':0
             }

if __name__ == '__main__':
    print('Why run this as a program?')
